"""Add Comment

Revision ID: 898023d8f230
Revises: 2e98d6a6835f
Create Date: 2026-01-23 14:49:11.827294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898023d8f230'
down_revision = '2e98d6a6835f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todo_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
